version: '3.7'
services:
  sub-diy:
    # image: joy88000/sub-diy:latest
    build: .
    container_name: sub-diy
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 7700:81
      - 7701:82
    volumes:
     - ./nginx/logs:/var/log/nginx/:rw